# Set theme
remote_theme: daviddarnes/alembic@main

# File excludes
exclude:
- README.md
- Gemfile
- Gemfile.lock

# Set plugins
plugins:
- jekyll-sitemap
- jekyll-mentions
- jekyll-paginate
- jekyll-seo-tag
- jekyll-redirect-from
- jekyll-feed
- jekyll-commonmark
- jekyll-include-cache
- jemoji
- jekyll-remote-theme

# Site settings
url: 'ea-uct.github.io'
baseurl: ''
title: 'Effective Altruism UCT'
description: 'An EA group based in Cape Town South Africa'
permalink: pretty
logo: "/assets/images/ea_uct_logo.png"

# Pagination
paginate: 5
paginate_path: posts/page:num

# Header nav
navigation_header:
- title: Home
  url: /
- title: Posts
  url: /posts/
- title: Categories
  url: /categories/
- title: Search
  url: /search/

# Footer nav
navigation_footer:
# - title: Back to top
#   url: "#top"

# Collections
collections:
  posts:
    title: Effective Altruism UCT Posts
    output: true
    description: ""
    feature_text: 
    feature_image: "/assets/images/cape_town_mountain.jpeg"

# Collection settings
defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: post # Set the default layout for posts
  -
    scope:
      path: ""
      type: "pages"
    values:
      layout: page # Set the default layout for pages

# 8. Site favicons & manifest icons
favicons: # Favicons are also used in the manifest file. Syntax is 'size: path'
  16: '/assets/logos/logo16px.png'
  32: '/assets/logos/logo32px.png'
  96: '/assets/logos/logo96px.png'
  120: '/assets/logos/logo120px.png'
  144: '/assets/logos/logo144px.png'
  180: '/assets/logos/logo180px.png'